config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users/homes#index"

  namespace :users do
    resources :users, only: :show
    get "/users_by_emails/:email" => "users_by_emails#show", param: :email, constraints: { email: /.*/ }
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :address1, presence: true
  validates :country, presence: true

  has_many_attached :images
  has_many :reviews, as: :reviewable
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user
  validates :images, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..(5.megabytes) }

  monetize :price_cents, allow_nil: true
  geocoded_by :address
  before_create :set_images

  #TODO change code to line one
  # after_validation :geocode, if: ->(obj){obj.address1.present? and obj.address1_changed? }
  after_validation :geocode, if: ->(obj){ obj.longitude.blank? and obj.latitude.blank? }

  def address
    # [address1, address2, city, state, country].compact.join(', ')
    [state, country].compact.join(', ')
  end

  def caculate_rating
    self.reviews.average(:rating).round(1)
  end

  private

  def set_images
    self.images.attach(io: File.open(File.join(Rails.root,'app/assets/images/982681.jpg')), filename: '982681')
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :reservation_end_date, presence: true
  validates :reservation_start_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true, counter_cache: true
  validates :title, presence: true
  validates :body, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  after_commit :update_average_rating

  private

  def update_average_rating
    reviewable.update!(average_rating: reviewable.reviews.average(:rating))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  after_create :set_profile
  has_many :favorites, dependent: :destroy
  has_many :favorited_properties, through: :favorites, source: :property
  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property
  private

  def set_profile
    self.profile = Profile.new
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :set_locale

  if Rails.env.production?

  rescue_from Exception, with: :rescue_500
  rescue_from ActionController::RoutingError, with: :rescue_404
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_404
  rescue_from ActionController::ParameterMissing, with: :rescue_400
  # rescue_from NotFound, with: :rescue_404
  # rescue_from Forbidden, with: :rescue_403
  end

  def rescue_400(exception)
    render json: { error: 'bad request' }, status: 400
  end

  def rescue_403(exception)
    render json: { error: 'not authorization' }, status: 403
  end

  def rescue_404(exception)
    render json: { error: 'not found' }, status: 404
  end

  def rescue_500(exception)
    render json: { error: 'internal server error' }, status: 500
  end

  protected

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @favorite = current_user.favorites.build(favorite_params)
    if @favorite.save
      respond_to do |format|
        format.json do
          render json: @favorite.to_json, status: :created
        end
      end
    else
      respond_to do |format|
        format.json do
          render json: { error: e.message }.to_json, status: 404
        end
      end
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy!

    respond_to do |format|
      format.json do
        render json: @favorite.to_json, status: 204
      end
    end
  end

  private

  def favorite_params
    params.require(:favorite).permit(:property_id)
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  include FavoriteHelper
  def index
    @properties = Property.all
  end

  # def get_distance
  #   if params[:latitide].blank? || params[:longitude].blank?
  #     render json: {
  #       success: false
  #     }
  #   else
  #     data = Property.all.map do |property|
  #             {
  #               Geocoder::Calculations.distance_between([property.latitude, property.longitude], [params[:latitide].to_f, params[:longitude].to_f])
  #             }
  #           end
  #     render json: {
  #       success: true,
  #       data: data
  #     }
  #     end
  #   end
  # end
end

app/controllers/users/users_by_emails_controller.rb
class Users::UsersByEmailsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    user = User.find_by!(email: params[:email])

    respond_to do |format|
      format.json do
        render json: user.to_json, status: :ok
      end
    end
  rescue ActiveRecord::RecordNotFound => e
    respond_to do |format|
      format.json do
        render json: { error: e.message }.to_json, status: 404
      end
    end
  end

end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :load_user, only: :show

  def show
    render json: @user.to_json, status: 200
  end

  protected

  def load_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
  def check_favorite_current_user? property
    Favorite.where(user: current_user, property: property).present?
  end

  def get_current_favorite_record property
    Favorite.where(user: current_user, property: property)&.last&.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vacation rental company</title>
    <%= favicon_link_tag 'favicon-custom.png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "users/shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/homes/_user_auth_form.html.erb
<div data-controller="users-by-email-auth">
  <div>
    <div class="flex">
      <div class="flex-none cursor-pointer" data-modal-target="closeButton">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="grow">
        <h3 class="pr-7 text-md leading-6 font-medium text-gray-900 text-center mb-4" id="modal-title">Log in or sign up</h3>
      </div>
    </div>

    <div class="relative">
      <div class="absolute inset-0 flex items-center" aria-hidden="true">
        <div class="w-full border-t border-gray-300"></div>
      </div>
    </div>

    <div class="clear"></div>

    <div class="pt-4">
      <h4 class="text-2xl leading-6 text-gray-900 mt-2 font-medium">Welcome to Airbnb</h4>

      <div data-users-by-email-auth-target="emailWrapper" class="relative mt-6 border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-black focus-within:border-black ">
        <label for="email" class="block text-xs font-medium text-gray-900 text-red-900">Email</label>
        <input data-users-by-email-auth-target="email" type="text" name="email" id="email" class="block w-full border-0 p-0 border-gray-300 text-gray-900 placeholder-gray-900 focus:ring-0 sm:text-sm border-red-300 text-red-900 placeholder-red-300" placeholder="joe.smith@gmail.com">
          <div data-users-by-email-auth-target="invalidSvg" class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
          <!-- Heroicon name: solid/exclamation-circle -->
            <svg class="h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
          </div>
      </div>
      <p data-users-by-email-auth-target="errorMessage" class="hidden mt-2 text-sm text-red-600" id="email-error">Your password must be less than 4 characters.</p>

    </div>
  </div>

  <div class="my-5 sm:my-6">
    <button data-users-by-email-auth-target="submit" type="button" class="w-full inline-flex justify-center items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2 airbnb-pink-gradient">Continue</button>
  </div>
</div>


<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="px-2 bg-white text-sm text-gray-500"> or </span>
  </div>
</div>

<div class="mt-5 sm:mt-6">
  <button type="button" class="w-full inline-flex justify-center items-center px-6 py-3 border border-black shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
    <svg class="-ml-1 mr-3 h-5 w-5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="presentation" aria-hidden="true" focusable="false" style="height: 20px; width: 20px; display: block; fill: currentcolor;"><defs><path id="a" d="M.001 0H24v23.854H.001z"></path></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"></use></mask><path d="M24 12c0-6.627-5.373-12-12-12S0 5.373 0 12c0 5.99 4.388 10.954 10.125 11.854V15.47H7.078V12h3.047V9.356c0-3.007 1.792-4.668 4.533-4.668 1.312 0 2.686.234 2.686.234v2.953H15.83c-1.491 0-1.956.925-1.956 1.874V12h3.328l-.532 3.469h-2.796v8.385C19.612 22.954 24 17.99 24 12" fill="#1877F2" mask="url(#b)"></path><path d="M16.671 15.469L17.203 12h-3.328V9.749c0-.949.465-1.874 1.956-1.874h1.513V4.922s-1.374-.234-2.686-.234c-2.741 0-4.533 1.66-4.533 4.668V12H7.078v3.469h3.047v8.385a12.09 12.09 0 003.75 0V15.47h2.796" fill="#FFF"></path></g></svg>
    Continue with Facebook
  </button>
</div>

app/views/users/homes/index.html.erb
<div class="container mx-auto px-18"
 data-controller="geolocation"
 data-latitude=""
 data-longitude="">
  <ul role="list" class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-4 sm:gap-x-6 lg:grid-cols-5 xl:gap-x-8">
    <%= render @properties %>
  </ul>
</div>

app/views/users/properties/_property.html.erb
<li class= "relative">
  <div class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 overflow-hidden">
    <%= image_tag property.images.first, class: "object-cover pointer-events-none group-hover:opacity-75"  if property.images.attached? %>
    <button type="button" class="absolute inset-0 focus:outline-none">
      <span class="sr-only">View details for IMG_4985.HEIC</span>
    </button>
     <div class="flex flex-row-reverse p-2">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          id="favorite-svg"
          class="h-8 w-8 cursor-pointer"
          data-controller= "favorite"
          data-favorited= "<%= check_favorite_current_user? property %>"
          data-userloggedin= "<%= user_signed_in? %>"
          data-userId= "<%= current_user&.id %>"
          data-propertyId= "<%= property.id %>"
          data-favoriteUrl= "<%= users_favorites_path %>"
          data-unFavoriteUrl= "<%= get_current_favorite_record(property).present? ? users_favorite_path(get_current_favorite_record(property)) : nil %>"
          data-action= "click->favorite#favorite"
          fill="<%= check_favorite_current_user?(property) ? "red" : "none" %>"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
      </div>
  </div>
  <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-events-none"><%= property.city %>, <%= property.state %> <%= property.country %></p>
  <p class="block text-sm font-medium text-gray-500 pointer-events-none text-black">
    <%= property.caculate_rating.round(1) %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline-block relative" viewBox="0 0 20 20" fill="currentColor" style="bottom: 2px;">
      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
    </svg>
  </p>
  <p class="block text-sm font-medium text-gray-500 pointer-events-none">20km</p>
  <p class="block text-sm font-medium text-gray-500 pointer-events-none">Jun 19-24</p>
  <p class="block text-sm font-medium text-gray-500 pointer-events-none"><%= humanized_money_with_symbol property.price %></p>
</li>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/shared/_modal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div
  data-controller="modal"
  id="modal-wrapper"
  class="hidden relative z-10"
  aria-labelledby="modal-title"
  role="dialog"
  aria-modal="true"
>
  <div class="hidden" id="modal-trigger" data-action="click->modal#showModal"></div>
  <!--
    Background backdrop, show/hide based on modal state.
    Entering: "ease-out duration-300"
      From: "opacity-0"
      To: "opacity-100"
    Leaving: "ease-in duration-200"
      From: "opacity-100"
      To: "opacity-0"
  -->
  <div
    id="modal-backdrop"
    class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
    data-transition-enter="ease-out duration-300"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in duration-200"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  ></div>

  <div class="fixed z-10 inset-0 overflow-y-auto">
    <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <!--
        Modal panel, show/hide based on modal state.
        Entering: "ease-out duration-300"
          From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          To: "opacity-100 translate-y-0 sm:scale-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100 translate-y-0 sm:scale-100"
          To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      -->
      <div
        id="modal-panel"
        class="hidden relative bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-xl sm:w-full sm:p-6"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      >
        <%= render modal_content %>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_modal_content.html.erb
<div data-controller="users-by-email-auth">
  <div>
    <div class="flex">
      <div class="flex-none cursor-pointer" data-modal-target="closeButton">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="grow">
        <h3 class="pr-7 text-md leading-6 font-medium text-gray-900 text-center mb-4" id="modal-title">Log in or sign up</h3>
      </div>
    </div>

    <div class="relative">
      <div class="absolute inset-0 flex items-center" aria-hidden="true">
        <div class="w-full border-t border-gray-300"></div>
      </div>
    </div>

    <div class="clear"></div>

    <div class="pt-4">
      <h4 class="text-2xl leading-6 text-gray-900 mt-2 font-medium">Welcome to Airbnb</h4>

      <div data-users-by-email-auth-target="emailWrapper" class="relative mt-6 border border-gray-300 rounded-md px-3 py-2 shadow-sm focus-within:ring-1 focus-within:ring-black focus-within:border-black ">
        <label for="email" class="block text-xs font-medium text-gray-900 text-red-900">Email</label>
        <input data-users-by-email-auth-target="email" type="text" name="email" id="email" class="block w-full border-0 p-0 border-gray-300 text-gray-900 placeholder-gray-900 focus:ring-0 sm:text-sm border-red-300 text-red-900 placeholder-red-300" placeholder="joe.smith@gmail.com">
          <div data-users-by-email-auth-target="invalidSvg" class="hidden absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
          <!-- Heroicon name: solid/exclamation-circle -->
            <svg class="h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
          </div>
      </div>
      <p data-users-by-email-auth-target="errorMessage" class="hidden mt-2 text-sm text-red-600" id="email-error">Your password must be less than 4 characters.</p>

    </div>
  </div>

  <div class="my-5 sm:my-6">
    <button data-users-by-email-auth-target="submit" type="button" class="w-full inline-flex justify-center items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2 airbnb-pink-gradient">Continue</button>
  </div>
</div>

<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="px-2 bg-white text-sm text-gray-500"> or </span>
  </div>
</div>

<div class="mt-5 sm:mt-6">
  <button type="button" class="w-full inline-flex justify-center items-center px-6 py-3 border border-black shadow-sm text-base font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
    <svg class="-ml-1 mr-3 h-5 w-5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" role="presentation" aria-hidden="true" focusable="false" style="height: 20px; width: 20px; display: block; fill: currentcolor;"><defs><path id="a" d="M.001 0H24v23.854H.001z"></path></defs><g fill="none" fill-rule="evenodd"><mask id="b" fill="#fff"><use xlink:href="#a"></use></mask><path d="M24 12c0-6.627-5.373-12-12-12S0 5.373 0 12c0 5.99 4.388 10.954 10.125 11.854V15.47H7.078V12h3.047V9.356c0-3.007 1.792-4.668 4.533-4.668 1.312 0 2.686.234 2.686.234v2.953H15.83c-1.491 0-1.956.925-1.956 1.874V12h3.328l-.532 3.469h-2.796v8.385C19.612 22.954 24 17.99 24 12" fill="#1877F2" mask="url(#b)"></path><path d="M16.671 15.469L17.203 12h-3.328V9.749c0-.949.465-1.874 1.956-1.874h1.513V4.922s-1.374-.234-2.686-.234c-2.741 0-4.533 1.66-4.533 4.668V12H7.078v3.469h3.047v8.385a12.09 12.09 0 003.75 0V15.47h2.796" fill="#FFF"></path></g></svg>
    Continue with Facebook
  </button>
</div>